fix: disable coverage step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,57 +40,58 @@ jobs:
           name: jacoco-report
           path: target/site/jacoco/
 
-  coverage:
-    name: "Generate Coverage Report"
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Download JaCoCo Coverage Report
-        uses: actions/download-artifact@v4
-        with:
-          name: jacoco-report
-          path: ./target/site/jacoco
-
-      - name: Generate Coverage Report
-        run: |
-          JACOCO_CSV="target/site/jacoco/jacoco.csv"
-          
-          if [[ ! -f "$JACOCO_CSV" ]]; then
-            echo "JaCoCo CSV file not found at $JACOCO_CSV"
-            exit 1
-          fi
-          
-          GLOBAL_COVERAGE=$(awk -F',' 'NR>1 {total+=$8} END {print total/NR"%"}' "$JACOCO_CSV")
-          LINE_COVERAGE=$(awk -F',' 'NR>1 {total+=$6} END {print total/NR"%"}' "$JACOCO_CSV")
-          BRANCH_COVERAGE=$(awk -F',' 'NR>1 {total+=$7} END {print total/NR"%"}' "$JACOCO_CSV")
-          
-          mkdir -p .github/test-coverage
-          
-          cat << EOF > .github/test-coverage/coverage.md
-          # 📊 Rapport de Couverture des Tests
-          
-          ## Vue d'ensemble
-          | Métrique            | Couverture | Statut |
-          |---------------------|------------|--------|
-          | Couverture Globale  | $GLOBAL_COVERAGE | $([ "${GLOBAL_COVERAGE//%/}" -ge 80 ] && echo "✅" || echo "❌") |
-          | Lignes de Code      | $LINE_COVERAGE | $([ "${LINE_COVERAGE//%/}" -ge 80 ] && echo "✅" || echo "❌") |
-          | Branches            | $BRANCH_COVERAGE | $([ "${BRANCH_COVERAGE//%/}" -ge 80 ] && echo "✅" || echo "❌") |
-          
-          ## ℹ️ Informations
-          - Dernière mise à jour : $(date '+%Y-%m-%d %H:%M:%S')
-          - Seuil minimal : 80%
-          EOF
-
-      - name: Commit Report
-        uses: EndBug/add-and-commit@v9
-        with:
-          default_author: github_actions
-          message: 'Mise à jour du rapport de couverture'
-          add: '.github/test-coverage/*'
-
+# TODO: one day...
+#  coverage:
+#    name: "Generate Coverage Report"
+#    runs-on: ubuntu-latest
+#    needs: build
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v4
+#
+#      - name: Download JaCoCo Coverage Report
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: jacoco-report
+#          path: ./target/site/jacoco
+#
+#      - name: Generate Coverage Report
+#        run: |
+#          JACOCO_CSV="target/site/jacoco/jacoco.csv"
+#
+#          if [[ ! -f "$JACOCO_CSV" ]]; then
+#            echo "JaCoCo CSV file not found at $JACOCO_CSV"
+#            exit 1
+#          fi
+#
+#          GLOBAL_COVERAGE=$(awk -F',' 'NR>1 {total+=$8} END {print total/NR"%"}' "$JACOCO_CSV")
+#          LINE_COVERAGE=$(awk -F',' 'NR>1 {total+=$6} END {print total/NR"%"}' "$JACOCO_CSV")
+#          BRANCH_COVERAGE=$(awk -F',' 'NR>1 {total+=$7} END {print total/NR"%"}' "$JACOCO_CSV")
+#
+#          mkdir -p .github/test-coverage
+#
+#          cat << EOF > .github/test-coverage/coverage.md
+#          # 📊 Rapport de Couverture des Tests
+#
+#          ## Vue d'ensemble
+#          | Métrique            | Couverture | Statut |
+#          |---------------------|------------|--------|
+#          | Couverture Globale  | $GLOBAL_COVERAGE | $([ "${GLOBAL_COVERAGE//%/}" -ge 80 ] && echo "✅" || echo "❌") |
+#          | Lignes de Code      | $LINE_COVERAGE | $([ "${LINE_COVERAGE//%/}" -ge 80 ] && echo "✅" || echo "❌") |
+#          | Branches            | $BRANCH_COVERAGE | $([ "${BRANCH_COVERAGE//%/}" -ge 80 ] && echo "✅" || echo "❌") |
+#
+#          ## ℹ️ Informations
+#          - Dernière mise à jour : $(date '+%Y-%m-%d %H:%M:%S')
+#          - Seuil minimal : 80%
+#          EOF
+#
+#      - name: Commit Report
+#        uses: EndBug/add-and-commit@v9
+#        with:
+#          default_author: github_actions
+#          message: 'Mise à jour du rapport de couverture'
+#          add: '.github/test-coverage/*'
+#
   docker:
     name: "Docker Build and Push"
     runs-on: ubuntu-latest
